### PR TITLE
Update authorized_keys

### PR DESCRIPTION
**Pull request by marcosdavid**

### CODE REVIEW

**Comment by dearing** [comment]
Paging @brint, @martinb3.

**Comment by martinb3** [comment]
We usually refer new UK rackers to get their merge from the existing UK rackers, @dearing, just FYI. They are much better able to verify the identity of any new Rackers vs. someone in the US.

**Comment by dearing** [comment]
@martinb3 I wasn't sure the contact for the UK to ping, so I used you as the closest I knew.

**Comment by martinb3** [comment]
Ah, okay. I'd probably still ping someone over there; I'm not _that_ much in the loop :)

**Pull request merged**
